#ifndef SURREALJ2534WRAPPER_GLOBAL_H
#define SURREALJ2534WRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SURREALJ2534WRAPPER_LIBRARY)
#  define SURREALJ2534WRAPPER_EXPORT extern "C" Q_DECL_EXPORT
#else
#  define SURREALJ2534WRAPPER_EXPORT extern "C" Q_DECL_IMPORT
#endif

#define GRETIO_SSL_REQUIRED


#endif // SURREALJ2534WRAPPER_GLOBAL_H
